[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps --force && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200